// BYU Pathway Tutorial Data
const tutorialData = [
    {
        id: 1,
        title: "Complete Registration Process",
        description: "Step-by-step guide through the entire BYU Pathway registration process from start to finish.",
        category: "registration",
        duration: 15,
        rating: 4.8,
        views: 1250,
        device: "pc",
        videoUrl: "https://youtu.be/mCZwO3zUDKo?si=fp42m96lZVP2t7jo",
        difficulty: "easy",
        image: "resources/registration-process.jpg"
    },
    {
        id: 2,
        title: "Master Canvas Navigation",
        description: "Learn all the essential features of Canvas to succeed in your online courses.",
        category: "canvas",
        duration: 25,
        rating: 4.9,
        views: 2100,
        device: "mobile",
        videoUrl: "https://www.youtube.com/embed/9bZkp7q19f0",
        difficulty: "medium",
        image: "resources/hero-main.jpg"
    },
    {
        id: 3,
        title: "Microsoft 365 Setup",
        description: "Complete setup guide for Word, Excel, PowerPoint, and Teams with your student account.",
        category: "microsoft",
        duration: 12,
        rating: 4.7,
        views: 980,
        device: "pc",
        videoUrl: "https://www.youtube.com/embed/kJQP7kiw5Fk",
        difficulty: "easy",
        image: "resources/microsoft365-setup.jpg"
    },
    {
        id: 4,
        title: "Portal Navigation",
        description: "Navigate the new BYU Pathway student portal like a pro with this comprehensive guide.",
        category: "portal",
        duration: 8,
        rating: 4.6,
        views: 750,
        device: "mobile",
        videoUrl: "https://www.youtube.com/embed/fJ9rUzIMcZQ",
        difficulty: "easy",
        image: "resources/mentor-support.jpg"
    },
    {
        id: 5,
        title: "Effective Study Skills",
        description: "Learn proven study techniques that will help you excel in your online courses.",
        category: "study-skills",
        duration: 18,
        rating: 4.8,
        views: 1800,
        device: "pc",
        videoUrl: "https://www.youtube.com/embed/OPf0YbXqDm0",
        difficulty: "medium",
        image: "resources/student-journey.jpg"
    },
    {
        id: 6,
        title: "Time Management Mastery",
        description: "Master time management techniques specifically designed for online students.",
        category: "time-management",
        duration: 22,
        rating: 4.9,
        views: 1650,
        device: "mobile",
        videoUrl: "https://www.youtube.com/embed/RgKAFK5djSk",
        difficulty: "medium",
        image: "resources/career-success.jpg"
    },
    {
        id: 7,
        title: "English Proficiency Basics",
        description: "Essential English skills to succeed in BYU Pathway courses and assignments.",
        category: "english",
        duration: 20,
        rating: 4.5,
        views: 1450,
        device: "pc",
        videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
        difficulty: "easy",
        image: "resources/hero-main.jpg"
    },
    {
        id: 8,
        title: "Weekly Gathering Participation",
        description: "How to join and get the most out of your weekly virtual or in-person gatherings.",
        category: "gathering",
        duration: 10,
        rating: 4.6,
        views: 1100,
        device: "mobile",
        videoUrl: "https://www.youtube.com/embed/J---aiyznGQ",
        difficulty: "easy",
        image: "resources/student-journey.jpg"
    },
    {
        id: 9,
        title: "Accessing Library Resources",
        description: "Learn how to find and use academic resources from the BYU Library system.",
        category: "resources",
        duration: 14,
        rating: 4.4,
        views: 920,
        device: "pc",
        videoUrl: "https://www.youtube.com/embed/09R8_2nJtjg",
        difficulty: "medium",
        image: "resources/mentor-support.jpg"
    },
    {
        id: 10,
        title: "Financial Aid Overview",
        description: "Complete guide to understanding financial aid options available for BYU Pathway students.",
        category: "financial",
        duration: 16,
        rating: 4.7,
        views: 2050,
        device: "pc",
        videoUrl: "https://www.youtube.com/embed/9bZkp7q19f0",
        difficulty: "easy",
        image: "resources/career-success.jpg"
    },
    {
        id: 11,
        title: "Submitting Assignments in Canvas",
        description: "Step-by-step process for uploading and submitting assignments successfully.",
        category: "canvas",
        duration: 12,
        rating: 4.6,
        views: 1870,
        device: "mobile",
        videoUrl: "https://www.youtube.com/embed/kJQP7kiw5Fk",
        difficulty: "easy",
        image: "resources/registration-process.jpg"
    },
    {
        id: 12,
        title: "Taking Proctored Exams",
        description: "What you need to know to successfully complete proctored exams in BYU Pathway.",
        category: "exams",
        duration: 18,
        rating: 4.8,
        views: 1560,
        device: "pc",
        videoUrl: "https://www.youtube.com/embed/fJ9rUzIMcZQ",
        difficulty: "medium",
        image: "resources/hero-main.jpg"
    },
    {
        id: 13,
        title: "Academic Calendar Navigation",
        description: "Understanding and navigating the BYU Pathway academic calendar and deadlines.",
        category: "academic",
        duration: 9,
        rating: 4.3,
        views: 890,
        device: "mobile",
        videoUrl: "https://www.youtube.com/embed/OPf0YbXqDm0",
        difficulty: "easy",
        image: "resources/microsoft365-setup.jpg"
    },
    {
        id: 14,
        title: "Peer Mentor Connection",
        description: "How to connect with and benefit from your assigned peer mentor.",
        category: "mentor",
        duration: 11,
        rating: 4.7,
        views: 1320,
        device: "pc",
        videoUrl: "https://www.youtube.com/embed/RgKAFK5djSk",
        difficulty: "easy",
        image: "resources/student-journey.jpg"
    },
    {
        id: 15,
        title: "Student Email Setup",
        description: "Setting up and managing your BYU Pathway student email account.",
        category: "microsoft",
        duration: 7,
        rating: 4.4,
        views: 1050,
        device: "mobile",
        videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
        difficulty: "easy",
        image: "resources/mentor-support.jpg"
    },
    {
        id: 16,
        title: "Using Discussion Forums",
        description: "Participating effectively in course discussion forums and group activities.",
        category: "canvas",
        duration: 13,
        rating: 4.5,
        views: 1430,
        device: "pc",
        videoUrl: "https://www.youtube.com/embed/J---aiyznGQ",
        difficulty: "medium",
        image: "resources/career-success.jpg"
    },
    {
        id: 17,
        title: "Course Materials Access",
        description: "How to access and download required textbooks and course materials.",
        category: "resources",
        duration: 10,
        rating: 4.6,
        views: 1280,
        device: "mobile",
        videoUrl: "https://www.youtube.com/embed/09R8_2nJtjg",
        difficulty: "easy",
        image: "resources/registration-process.jpg"
    },
    {
        id: 18,
        title: "Creating Study Groups",
        description: "Forming and participating in effective study groups with fellow students.",
        category: "study-skills",
        duration: 15,
        rating: 4.7,
        views: 1190,
        device: "pc",
        videoUrl: "https://www.youtube.com/embed/9bZkp7q19f0",
        difficulty: "medium",
        image: "resources/student-journey.jpg"
    },
    {
        id: 19,
        title: "Transcript Requests",
        description: "How to request official and unofficial transcripts during and after your program.",
        category: "academic",
        duration: 8,
        rating: 4.5,
        views: 980,
        device: "mobile",
        videoUrl: "https://www.youtube.com/embed/kJQP7kiw5Fk",
        difficulty: "easy",
        image: "resources/microsoft365-setup.jpg"
    },
    {
        id: 20,
        title: "Degree Audit Review",
        description: "Understanding and interpreting your degree audit to track progress.",
        category: "academic",
        duration: 14,
        rating: 4.8,
        views: 1670,
        device: "pc",
        videoUrl: "https://www.youtube.com/embed/fJ9rUzIMcZQ",
        difficulty: "medium",
        image: "resources/mentor-support.jpg"
    },
    {
        id: 21,
        title: "Online Etiquette and Netiquette",
        description: "Best practices for communication and interaction in online classes.",
        category: "study-skills",
        duration: 12,
        rating: 4.4,
        views: 1020,
        device: "mobile",
        videoUrl: "https://www.youtube.com/embed/OPf0YbXqDm0",
        difficulty: "easy",
        image: "resources/hero-main.jpg"
    },
    {
        id: 22,
        title: "Accessing Tech Support",
        description: "How to get technical help when you encounter system or software issues.",
        category: "technical",
        duration: 9,
        rating: 4.6,
        views: 1350,
        device: "pc",
        videoUrl: "https://www.youtube.com/embed/RgKAFK5djSk",
        difficulty: "easy",
        image: "resources/career-success.jpg"
    },
    {
        id: 23,
        title: "Career Services Introduction",
        description: "Getting started with BYU Pathway's career services and job placement assistance.",
        category: "career",
        duration: 16,
        rating: 4.9,
        views: 1890,
        device: "pc",
        videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
        difficulty: "easy",
        image: "resources/registration-process.jpg"
    },
    {
        id: 24,
        title: "Using the Pathway Portal App",
        description: "Navigating the mobile app for BYU Pathway portal access on-the-go.",
        category: "portal",
        duration: 11,
        rating: 4.5,
        views: 1170,
        device: "mobile",
        videoUrl: "https://www.youtube.com/embed/J---aiyznGQ",
        difficulty: "medium",
        image: "resources/student-journey.jpg"
    },
    {
        id: 25,
        title: "Setting Up Two-Factor Authentication",
        description: "Securing your accounts with two-factor authentication for enhanced security.",
        category: "security",
        duration: 10,
        rating: 4.7,
        views: 1420,
        device: "pc",
        videoUrl: "https://www.youtube.com/embed/09R8_2nJtjg",
        difficulty: "medium",
        image: "resources/microsoft365-setup.jpg"
    },
    {
        id: 26,
        title: "Accessing Mental Health Resources",
        description: "Finding and utilizing mental health and wellness resources available to students.",
        category: "wellness",
        duration: 13,
        rating: 4.6,
        views: 980,
        device: "mobile",
        videoUrl: "https://www.youtube.com/embed/9bZkp7q19f0",
        difficulty: "easy",
        image: "resources/mentor-support.jpg"
    },
    {
        id: 27,
        title: "Using Office Hours Effectively",
        description: "Making the most of instructor office hours to enhance your learning.",
        category: "study-skills",
        duration: 14,
        rating: 4.8,
        views: 1560,
        device: "pc",
        videoUrl: "https://www.youtube.com/embed/kJQP7kiw5Fk",
        difficulty: "medium",
        image: "resources/career-success.jpg"
    },
    {
        id: 28,
        title: "Creating a Study Schedule",
        description: "Developing and maintaining an effective study schedule for online learning.",
        category: "time-management",
        duration: 17,
        rating: 4.5,
        views: 1290,
        device: "mobile",
        videoUrl: "https://www.youtube.com/embed/fJ9rUzIMcZQ",
        difficulty: "easy",
        image: "resources/registration-process.jpg"
    },
    {
        id: 29,
        title: "Using Digital Note-Taking Tools",
        description: "Leveraging digital tools for effective note-taking in online courses.",
        category: "tools",
        duration: 15,
        rating: 4.7,
        views: 1430,
        device: "pc",
        videoUrl: "https://www.youtube.com/embed/OPf0YbXqDm0",
        difficulty: "medium",
        image: "resources/student-journey.jpg"
    },
    {
        id: 30,
        title: "Understanding Course Syllabi",
        description: "Deciphering and using course syllabi to maximize your academic success.",
        category: "academic",
        duration: 12,
        rating: 4.4,
        views: 1150,
        device: "pc",
        videoUrl: "https://www.youtube.com/embed/RgKAFK5djSk",
        difficulty: "easy",
        image: "resources/hero-main.jpg"
    },
    {
        id: 31,
        title: "Canvas Mobile App Features",
        description: "Using the Canvas mobile app to stay connected to your courses anywhere.",
        category: "canvas",
        duration: 10,
        rating: 4.6,
        views: 1340,
        device: "mobile",
        videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
        difficulty: "easy",
        image: "resources/microsoft365-setup.jpg"
    },
    {
        id: 32,
        title: "Preparing for Graduation",
        description: "Steps to take to prepare for graduation and post-program opportunities.",
        category: "academic",
        duration: 18,
        rating: 4.9,
        views: 1680,
        device: "pc",
        videoUrl: "https://www.youtube.com/embed/J---aiyznGQ",
        difficulty: "medium",
        image: "resources/mentor-support.jpg"
    },
    {
        id: 33,
        title: "Utilizing Peer Feedback",
        description: "Effectively giving and receiving feedback from fellow students.",
        category: "study-skills",
        duration: 13,
        rating: 4.5,
        views: 1080,
        device: "mobile",
        videoUrl: "https://www.youtube.com/embed/09R8_2nJtjg",
        difficulty: "medium",
        image: "resources/career-success.jpg"
    },
    {
        id: 34,
        title: "Managing Group Projects",
        description: "Collaborating effectively on group projects in an online environment.",
        category: "study-skills",
        duration: 19,
        rating: 4.7,
        views: 1520,
        device: "pc",
        videoUrl: "https://www.youtube.com/embed/9bZkp7q19f0",
        difficulty: "medium",
        image: "resources/registration-process.jpg"
    },
    {
        id: 35,
        title: "Accessing Disability Services",
        description: "Resources and accommodations available for students with disabilities.",
        category: "services",
        duration: 11,
        rating: 4.6,
        views: 890,
        device: "mobile",
        videoUrl: "https://www.youtube.com/embed/kJQP7kiw5Fk",
        difficulty: "easy",
        image: "resources/student-journey.jpg"
    },
    {
        id: 36,
        title: "Using PathwayConnect Resources",
        description: "Maximizing your success in the foundational PathwayConnect program.",
        category: "pathwayconnect",
        duration: 14,
        rating: 4.8,
        views: 1750,
        device: "pc",
        videoUrl: "https://www.youtube.com/embed/fJ9rUzIMcZQ",
        difficulty: "easy",
        image: "resources/hero-main.jpg"
    },
    {
        id: 37,
        title: "Building Professional Networks",
        description: "Connecting with professionals and alumni to advance your career.",
        category: "career",
        duration: 16,
        rating: 4.7,
        views: 1460,
        device: "pc",
        videoUrl: "https://www.youtube.com/embed/OPf0YbXqDm0",
        difficulty: "medium",
        image: "resources/microsoft365-setup.jpg"
    },
    {
        id: 38,
        title: "Using Financial Planning Tools",
        description: "Tools and resources to manage finances during your studies.",
        category: "financial",
        duration: 12,
        rating: 4.5,
        views: 1230,
        device: "mobile",
        videoUrl: "https://www.youtube.com/embed/RgKAFK5djSk",
        difficulty: "medium",
        image: "resources/mentor-support.jpg"
    },
    {
        id: 39,
        title: "Understanding Academic Integrity",
        description: "Principles and practices of academic integrity at BYU Pathway.",
        category: "academic",
        duration: 10,
        rating: 4.4,
        views: 1120,
        device: "pc",
        videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
        difficulty: "easy",
        image: "resources/career-success.jpg"
    },
    {
        id: 40,
        title: "Staying Motivated Online",
        description: "Strategies for maintaining motivation throughout your online learning journey.",
        category: "wellness",
        duration: 15,
        rating: 4.8,
        views: 1670,
        device: "mobile",
        videoUrl: "https://www.youtube.com/embed/J---aiyznGQ",
        difficulty: "medium",
        image: "resources/registration-process.jpg"
    },
    {
        id: 41,
        title: "Using Online Libraries",
        description: "Accessing and searching academic databases and online libraries.",
        category: "resources",
        duration: 13,
        rating: 4.6,
        views: 1380,
        device: "pc",
        videoUrl: "https://www.youtube.com/embed/09R8_2nJtjg",
        difficulty: "medium",
        image: "resources/student-journey.jpg"
    },
    {
        id: 42,
        title: "Preparing for Transfer Credits",
        description: "Understanding how transfer credits work when entering BYU Pathway.",
        category: "academic",
        duration: 17,
        rating: 4.5,
        views: 980,
        device: "pc",
        videoUrl: "https://www.youtube.com/embed/9bZkp7q19f0",
        difficulty: "medium",
        image: "resources/hero-main.jpg"
    },
    {
        id: 43,
        title: "Using Citation Tools",
        description: "Properly citing sources and avoiding plagiarism in your assignments.",
        category: "academic",
        duration: 11,
        rating: 4.4,
        views: 1150,
        device: "mobile",
        videoUrl: "https://www.youtube.com/embed/kJQP7kiw5Fk",
        difficulty: "medium",
        image: "resources/microsoft365-setup.jpg"
    },
    {
        id: 44,
        title: "Optimizing Your Workspace",
        description: "Creating an effective study environment at home for online learning.",
        category: "wellness",
        duration: 14,
        rating: 4.7,
        views: 1420,
        device: "pc",
        videoUrl: "https://www.youtube.com/embed/fJ9rUzIMcZQ",
        difficulty: "easy",
        image: "resources/mentor-support.jpg"
    },
    {
        id: 45,
        title: "Managing Stress and Anxiety",
        description: "Techniques for managing academic stress and anxiety during your studies.",
        category: "wellness",
        duration: 18,
        rating: 4.8,
        views: 1560,
        device: "mobile",
        videoUrl: "https://www.youtube.com/embed/OPf0YbXqDm0",
        difficulty: "medium",
        image: "resources/career-success.jpg"
    },
    {
        id: 46,
        title: "Using Assessment Feedback",
        description: "Understanding and applying feedback from instructors to improve performance.",
        category: "study-skills",
        duration: 12,
        rating: 4.6,
        views: 1290,
        device: "pc",
        videoUrl: "https://www.youtube.com/embed/RgKAFK5djSk",
        difficulty: "medium",
        image: "resources/registration-process.jpg"
    },
    {
        id: 47,
        title: "Exploring Career Paths",
        description: "Identifying and exploring career paths that align with your interests and goals.",
        category: "career",
        duration: 16,
        rating: 4.9,
        views: 1840,
        device: "pc",
        videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
        difficulty: "easy",
        image: "resources/student-journey.jpg"
    },
    {
        id: 48,
        title: "Creating a Professional Portfolio",
        description: "Building a portfolio to showcase your academic and professional accomplishments.",
        category: "career",
        duration: 20,
        rating: 4.7,
        views: 1480,
        device: "mobile",
        videoUrl: "https://www.youtube.com/embed/J---aiyznGQ",
        difficulty: "medium",
        image: "resources/hero-main.jpg"
    },
    {
        id: 49,
        title: "Using Video Conferencing Tools",
        description: "Best practices for participating in virtual classes and meetings.",
        category: "tools",
        duration: 10,
        rating: 4.5,
        views: 1210,
        device: "pc",
        videoUrl: "https://www.youtube.com/embed/09R8_2nJtjg",
        difficulty: "easy",
        image: "resources/microsoft365-setup.jpg"
    },
    {
        id: 50,
        title: "Developing Critical Thinking",
        description: "Enhancing critical thinking skills for academic and professional success.",
        category: "study-skills",
        duration: 19,
        rating: 4.8,
        views: 1650,
        device: "pc",
        videoUrl: "https://www.youtube.com/embed/9bZkp7q19f0",
        difficulty: "medium",
        image: "resources/mentor-support.jpg"
    },
    {
        id: 51,
        title: "Using Grammar and Writing Tools",
        description: "Improving your writing with available grammar and composition tools.",
        category: "english",
        duration: 15,
        rating: 4.6,
        views: 1370,
        device: "mobile",
        videoUrl: "https://www.youtube.com/embed/kJQP7kiw5Fk",
        difficulty: "medium",
        image: "resources/career-success.jpg"
    },
    {
        id: 52,
        title: "Navigating Cultural Differences",
        description: "Understanding and adapting to cultural differences in an international program.",
        category: "wellness",
        duration: 14,
        rating: 4.7,
        views: 1190,
        device: "pc",
        videoUrl: "https://www.youtube.com/embed/fJ9rUzIMcZQ",
        difficulty: "medium",
        image: "resources/registration-process.jpg"
    },
    {
        id: 53,
        title: "Balancing Work and Study",
        description: "Managing responsibilities when balancing employment and academic commitments.",
        category: "time-management",
        duration: 17,
        rating: 4.8,
        views: 1580,
        device: "mobile",
        videoUrl: "https://www.youtube.com/embed/OPf0YbXqDm0",
        difficulty: "medium",
        image: "resources/student-journey.jpg"
    },
    {
        id: 54,
        title: "Using Backup Systems",
        description: "Protecting your academic work with effective backup strategies.",
        category: "technical",
        duration: 11,
        rating: 4.5,
        views: 1040,
        device: "pc",
        videoUrl: "https://www.youtube.com/embed/RgKAFK5djSk",
        difficulty: "medium",
        image: "resources/hero-main.jpg"
    },
    {
        id: 55,
        title: "Understanding Grading Rubrics",
        description: "Decoding grading rubrics to better understand assignment expectations.",
        category: "academic",
        duration: 13,
        rating: 4.6,
        views: 1360,
        device: "pc",
        videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
        difficulty: "easy",
        image: "resources/microsoft365-setup.jpg"
    },
    {
        id: 56,
        title: "Accessing Scholarship Opportunities",
        description: "Finding and applying for scholarships to fund your education.",
        category: "financial",
        duration: 16,
        rating: 4.9,
        views: 1720,
        device: "mobile",
        videoUrl: "https://www.youtube.com/embed/J---aiyznGQ",
        difficulty: "easy",
        image: "resources/mentor-support.jpg"
    },
    {
        id: 57,
        title: "Using Digital Organization Tools",
        description: "Organizing your academic life with digital calendars, planners, and tools.",
        category: "tools",
        duration: 12,
        rating: 4.5,
        views: 1240,
        device: "pc",
        videoUrl: "https://www.youtube.com/embed/09R8_2nJtjg",
        difficulty: "medium",
        image: "resources/career-success.jpg"
    },
    {
        id: 58,
        title: "Engaging with Faculty",
        description: "Building positive relationships with faculty members and instructors.",
        category: "academic",
        duration: 14,
        rating: 4.7,
        views: 1450,
        device: "mobile",
        videoUrl: "https://www.youtube.com/embed/9bZkp7q19f0",
        difficulty: "medium",
        image: "resources/registration-process.jpg"
    },
    {
        id: 59,
        title: "Developing Soft Skills",
        description: "Enhancing communication, teamwork, and leadership abilities.",
        category: "career",
        duration: 18,
        rating: 4.8,
        views: 1680,
        device: "pc",
        videoUrl: "https://www.youtube.com/embed/kJQP7kiw5Fk",
        difficulty: "medium",
        image: "resources/student-journey.jpg"
    },
    {
        id: 60,
        title: "Using Language Learning Apps",
        description: "Supplementing English proficiency with language learning applications.",
        category: "english",
        duration: 10,
        rating: 4.4,
        views: 1130,
        device: "mobile",
        videoUrl: "https://www.youtube.com/embed/fJ9rUzIMcZQ",
        difficulty: "easy",
        image: "resources/hero-main.jpg"
    },
    {
        id: 61,
        title: "Preparing for Internships",
        description: "Getting ready for internship opportunities during or after your program.",
        category: "career",
        duration: 15,
        rating: 4.9,
        views: 1590,
        device: "pc",
        videoUrl: "https://www.youtube.com/embed/OPf0YbXqDm0",
        difficulty: "medium",
        image: "resources/microsoft365-setup.jpg"
    },
    {
        id: 62,
        title: "Understanding Academic Probation",
        description: "What academic probation means and how to improve your standing.",
        category: "academic",
        duration: 13,
        rating: 4.6,
        views: 980,
        device: "pc",
        videoUrl: "https://www.youtube.com/embed/RgKAFK5djSk",
        difficulty: "easy",
        image: "resources/mentor-support.jpg"
    },
    {
        id: 63,
        title: "Using Mind Mapping Software",
        description: "Visualizing ideas and concepts with digital mind mapping tools.",
        category: "tools",
        duration: 11,
        rating: 4.5,
        views: 1270,
        device: "mobile",
        videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
        difficulty: "medium",
        image: "resources/career-success.jpg"
    },
    {
        id: 64,
        title: "Managing Multiple Courses",
        description: "Effectively juggling multiple courses simultaneously without becoming overwhelmed.",
        category: "time-management",
        duration: 16,
        rating: 4.7,
        views: 1510,
        device: "pc",
        videoUrl: "https://www.youtube.com/embed/J---aiyznGQ",
        difficulty: "medium",
        image: "resources/registration-process.jpg"
    },
    {
        id: 65,
        title: "Understanding Credit Hours",
        description: "How credit hours work and how they impact your academic progress.",
        category: "academic",
        duration: 9,
        rating: 4.4,
        views: 1090,
        device: "mobile",
        videoUrl: "https://www.youtube.com/embed/09R8_2nJtjg",
        difficulty: "easy",
        image: "resources/student-journey.jpg"
    },
    {
        id: 66,
        title: "Using Plagiarism Detection Tools",
        description: "Ensuring originality in your work with plagiarism detection software.",
        category: "academic",
        duration: 12,
        rating: 4.6,
        views: 1340,
        device: "pc",
        videoUrl: "https://www.youtube.com/embed/9bZkp7q19f0",
        difficulty: "medium",
        image: "resources/hero-main.jpg"
    },
    {
        id: 67,
        title: "Developing Presentation Skills",
        description: "Creating and delivering effective presentations in an online environment.",
        category: "study-skills",
        duration: 17,
        rating: 4.8,
        views: 1480,
        device: "mobile",
        videoUrl: "https://www.youtube.com/embed/kJQP7kiw5Fk",
        difficulty: "medium",
        image: "resources/microsoft365-setup.jpg"
    },
    {
        id: 68,
        title: "Using Accessibility Features",
        description: "Accessing built-in accessibility features to enhance your learning experience.",
        category: "services",
        duration: 10,
        rating: 4.5,
        views: 1160,
        device: "pc",
        videoUrl: "https://www.youtube.com/embed/fJ9rUzIMcZQ",
        difficulty: "easy",
        image: "resources/mentor-support.jpg"
    },
    {
        id: 69,
        title: "Preparing for Job Interviews",
        description: "Mastering virtual and in-person interview techniques for career success.",
        category: "career",
        duration: 19,
        rating: 4.9,
        views: 1750,
        device: "pc",
        videoUrl: "https://www.youtube.com/embed/OPf0YbXqDm0",
        difficulty: "medium",
        image: "resources/career-success.jpg"
    },
    {
        id: 70,
        title: "Creating Effective Resumes",
        description: "Crafting resumes that highlight your academic achievements and skills.",
        category: "career",
        duration: 14,
        rating: 4.7,
        views: 1420,
        device: "mobile",
        videoUrl: "https://www.youtube.com/embed/RgKAFK5djSk",
        difficulty: "medium",
        image: "resources/registration-process.jpg"
    },
    {
        id: 71,
        title: "Understanding GPA Calculations",
        description: "How your GPA is calculated and how to improve it consistently.",
        category: "academic",
        duration: 11,
        rating: 4.4,
        views: 1230,
        device: "pc",
        videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
        difficulty: "medium",
        image: "resources/student-journey.jpg"
    },
    {
        id: 72,
        title: "Using Cloud Storage Solutions",
        description: "Securely storing and accessing your academic files across devices.",
        category: "tools",
        duration: 13,
        rating: 4.6,
        views: 1370,
        device: "mobile",
        videoUrl: "https://www.youtube.com/embed/J---aiyznGQ",
        difficulty: "easy",
        image: "resources/hero-main.jpg"
    },
    {
        id: 73,
        title: "Dealing with Academic Dishonesty Allegations",
        description: "Understanding policies and procedures if faced with academic dishonesty claims.",
        category: "academic",
        duration: 15,
        rating: 4.5,
        views: 980,
        device: "pc",
        videoUrl: "https://www.youtube.com/embed/09R8_2nJtjg",
        difficulty: "medium",
        image: "resources/microsoft365-setup.jpg"
    },
    {
        id: 74,
        title: "Using Screen Readers and Assistive Technology",
        description: "Making the most of assistive technologies for accessible learning.",
        category: "accessibility",
        duration: 12,
        rating: 4.7,
        views: 1140,
        device: "pc",
        videoUrl: "https://www.youtube.com/embed/9bZkp7q19f0",
        difficulty: "medium",
        image: "resources/mentor-support.jpg"
    },
    {
        id: 75,
        title: "Developing Emotional Intelligence",
        description: "Building emotional intelligence for better relationships and outcomes.",
        category: "wellness",
        duration: 18,
        rating: 4.8,
        views: 1560,
        device: "mobile",
        videoUrl: "https://www.youtube.com/embed/kJQP7kiw5Fk",
        difficulty: "medium",
        image: "resources/career-success.jpg"
    },
    {
        id: 76,
        title: "Optimizing Internet for Classes",
        description: "Ensuring reliable internet connectivity for synchronous classes and exams.",
        category: "technical",
        duration: 10,
        rating: 4.4,
        views: 1080,
        device: "pc",
        videoUrl: "https://www.youtube.com/embed/fJ9rUzIMcZQ",
        difficulty: "easy",
        image: "resources/registration-process.jpg"
    },
    {
        id: 77,
        title: "Understanding Transfer Agreements",
        description: "Learning about articulation agreements for transferring to other institutions.",
        category: "academic",
        duration: 14,
        rating: 4.6,
        views: 1290,
        device: "mobile",
        videoUrl: "https://www.youtube.com/embed/OPf0YbXqDm0",
        difficulty: "medium",
        image: "resources/student-journey.jpg"
    },
    {
        id: 78,
        title: "Using Virtual Reality Learning Tools",
        description: "Exploring immersive learning experiences with VR technology.",
        category: "tools",
        duration: 16,
        rating: 4.9,
        views: 1450,
        device: "pc",
        videoUrl: "https://www.youtube.com/embed/RgKAFK5djSk",
        difficulty: "medium",
        image: "resources/hero-main.jpg"
    },
    {
        id: 79,
        title: "Developing Leadership Skills",
        description: "Building leadership capabilities through coursework and extracurriculars.",
        category: "career",
        duration: 17,
        rating: 4.7,
        views: 1620,
        device: "pc",
        videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
        difficulty: "medium",
        image: "resources/microsoft365-setup.jpg"
    },
    {
        id: 80,
        title: "Preparing for Standardized Tests",
        description: "Getting ready for tests that may be required for graduation or transfer.",
        category: "academic",
        duration: 19,
        rating: 4.5,
        views: 1380,
        device: "mobile",
        videoUrl: "https://www.youtube.com/embed/J---aiyznGQ",
        difficulty: "hard",
        image: "resources/mentor-support.jpg"
    },
    {
        id: 81,
        title: "Using AI Tools Responsibly",
        description: "Understanding how to appropriately incorporate AI tools in your studies.",
        category: "tools",
        duration: 11,
        rating: 4.8,
        views: 1540,
        device: "pc",
        videoUrl: "https://www.youtube.com/embed/09R8_2nJtjg",
        difficulty: "medium",
        image: "resources/career-success.jpg"
    },
    {
        id: 82,
        title: "Developing Cultural Competency",
        description: "Building skills to interact effectively with people from diverse backgrounds.",
        category: "wellness",
        duration: 15,
        rating: 4.6,
        views: 1270,
        device: "mobile",
        videoUrl: "https://www.youtube.com/embed/9bZkp7q19f0",
        difficulty: "medium",
        image: "resources/registration-process.jpg"
    },
    {
        id: 83,
        title: "Managing Course Withdrawals",
        description: "Understanding the process and implications of withdrawing from courses.",
        category: "academic",
        duration: 13,
        rating: 4.4,
        views: 1020,
        device: "pc",
        videoUrl: "https://www.youtube.com/embed/kJQP7kiw5Fk",
        difficulty: "easy",
        image: "resources/student-journey.jpg"
    },
    {
        id: 84,
        title: "Using Augmented Reality Learning Apps",
        description: "Exploring AR applications that enhance learning experiences.",
        category: "tools",
        duration: 14,
        rating: 4.7,
        views: 1390,
        device: "mobile",
        videoUrl: "https://www.youtube.com/embed/fJ9rUzIMcZQ",
        difficulty: "medium",
        image: "resources/hero-main.jpg"
    },
    {
        id: 85,
        title: "Building Professional Identity",
        description: "Establishing your professional brand and identity during your studies.",
        category: "career",
        duration: 18,
        rating: 4.9,
        views: 1580,
        device: "pc",
        videoUrl: "https://www.youtube.com/embed/OPf0YbXqDm0",
        difficulty: "medium",
        image: "resources/microsoft365-setup.jpg"
    },
    {
        id: 86,
        title: "Understanding Financial Literacy",
        description: "Learning essential money management skills for students and beyond.",
        category: "financial",
        duration: 16,
        rating: 4.6,
        views: 1430,
        device: "mobile",
        videoUrl: "https://www.youtube.com/embed/RgKAFK5djSk",
        difficulty: "medium",
        image: "resources/mentor-support.jpg"
    },
    {
        id: 87,
        title: "Using Collaborative Platforms",
        description: "Leveraging platforms that enable effective collaboration with classmates.",
        category: "tools",
        duration: 12,
        rating: 4.5,
        views: 1250,
        device: "pc",
        videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
        difficulty: "medium",
        image: "resources/career-success.jpg"
    },
    {
        id: 88,
        title: "Developing Cross-Cultural Communication",
        description: "Enhancing communication skills for diverse, international environments.",
        category: "study-skills",
        duration: 17,
        rating: 4.8,
        views: 1470,
        device: "mobile",
        videoUrl: "https://www.youtube.com/embed/J---aiyznGQ",
        difficulty: "medium",
        image: "resources/registration-process.jpg"
    },
    {
        id: 89,
        title: "Preparing for Capstone Projects",
        description: "Strategies for successfully completing culminating capstone experiences.",
        category: "academic",
        duration: 20,
        rating: 4.7,
        views: 1630,
        device: "pc",
        videoUrl: "https://www.youtube.com/embed/09R8_2nJtjg",
        difficulty: "hard",
        image: "resources/student-journey.jpg"
    },
    {
        id: 90,
        title: "Using Data Visualization Tools",
        description: "Presenting information effectively with charts, graphs, and visualizations.",
        category: "tools",
        duration: 14,
        rating: 4.6,
        views: 1360,
        device: "pc",
        videoUrl: "https://www.youtube.com/embed/9bZkp7q19f0",
        difficulty: "medium",
        image: "resources/hero-main.jpg"
    },
    {
        id: 91,
        title: "Developing Research Skills",
        description: "Building capabilities for conducting academic and professional research.",
        category: "study-skills",
        duration: 18,
        rating: 4.8,
        views: 1520,
        device: "mobile",
        videoUrl: "https://www.youtube.com/embed/kJQP7kiw5Fk",
        difficulty: "medium",
        image: "resources/microsoft365-setup.jpg"
    },
    {
        id: 92,
        title: "Understanding Intellectual Property",
        description: "Learning about copyright, fair use, and intellectual property rights.",
        category: "academic",
        duration: 13,
        rating: 4.5,
        views: 1190,
        device: "pc",
        videoUrl: "https://www.youtube.com/embed/fJ9rUzIMcZQ",
        difficulty: "medium",
        image: "resources/mentor-support.jpg"
    },
    {
        id: 93,
        title: "Using Performance Analytics",
        description: "Tracking and improving your academic performance with data analytics.",
        category: "academic",
        duration: 15,
        rating: 4.7,
        views: 1440,
        device: "mobile",
        videoUrl: "https://www.youtube.com/embed/OPf0YbXqDm0",
        difficulty: "medium",
        image: "resources/career-success.jpg"
    },
    {
        id: 94,
        title: "Preparing for Professional Certifications",
        description: "Getting ready for industry-recognized professional certifications.",
        category: "career",
        duration: 16,
        rating: 4.9,
        views: 1670,
        device: "pc",
        videoUrl: "https://www.youtube.com/embed/RgKAFK5djSk",
        difficulty: "hard",
        image: "resources/registration-process.jpg"
    },
    {
        id: 95,
        title: "Using Adaptive Learning Systems",
        description: "Personalizing your education with AI-powered adaptive learning platforms.",
        category: "tools",
        duration: 12,
        rating: 4.6,
        views: 1320,
        device: "mobile",
        videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
        difficulty: "medium",
        image: "resources/student-journey.jpg"
    },
    {
        id: 96,
        title: "Developing Crisis Management Skills",
        description: "Building resilience and crisis management capabilities for unexpected situations.",
        category: "wellness",
        duration: 17,
        rating: 4.8,
        views: 1480,
        device: "pc",
        videoUrl: "https://www.youtube.com/embed/J---aiyznGQ",
        difficulty: "hard",
        image: "resources/hero-main.jpg"
    },
    {
        id: 97,
        title: "Using Blockchain for Academic Credentials",
        description: "Understanding emerging blockchain technology for credential verification.",
        category: "technical",
        duration: 14,
        rating: 4.5,
        views: 1230,
        device: "pc",
        videoUrl: "https://www.youtube.com/embed/09R8_2nJtjg",
        difficulty: "medium",
        image: "resources/microsoft365-setup.jpg"
    },
    {
        id: 98,
        title: "Developing Innovation Mindset",
        description: "Cultivating creativity and innovation for solving complex problems.",
        category: "career",
        duration: 19,
        rating: 4.7,
        views: 1560,
        device: "mobile",
        videoUrl: "https://www.youtube.com/embed/9bZkp7q19f0",
        difficulty: "hard",
        image: "resources/mentor-support.jpg"
    },
    {
        id: 99,
        title: "Preparing for Graduate Studies",
        description: "Planning for advanced degrees after completing your undergraduate program.",
        category: "academic",
        duration: 16,
        rating: 4.8,
        views: 1410,
        device: "pc",
        videoUrl: "https://www.youtube.com/embed/kJQP7kiw5Fk",
        difficulty: "medium",
        image: "resources/career-success.jpg"
    },
    {
        id: 100,
        title: "Embracing Lifelong Learning",
        description: "Adopting a mindset for continuous learning and skill development.",
        category: "wellness",
        duration: 15,
        rating: 4.9,
        views: 1780,
        device: "mobile",
        videoUrl: "https://www.youtube.com/embed/fJ9rUzIMcZQ",
        difficulty: "easy",
        image: "resources/hero-main.jpg"
    }
];